# Generated by Django 4.1.2 on 2026-08-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=500, verbose_name='Surname')),
                ('telephone', models.CharField(max_length=500, verbose_name='Telephone')),
                ('telegram', models.CharField(blank=True, max_length=500, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_birth', models.DateField(blank=True, verbose_name='Date of birth')),
                ('allegria', models.BooleanField(default=False, verbose_name='Allegria')),
                ('client_source', models.CharField(blank=True, max_length=500, verbose_name='Client Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('whose_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
