# Generated by Django 4.1.2 on 2026-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0003_client'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('whose_client', 'telephone'), name='unique_client_phone_per_user'),
        ),
    ]
