# Generated by Django 4.1.2 on 2026-08-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0004_client_unique_client_phone_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
