# Generated by Django 4.1.2 on 2026-08-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0005_alter_client_date_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField(verbose_name='Date of session')),
                ('time_start', models.TimeField(verbose_name='Time start')),
                ('duration_minutes', models.IntegerField(verbose_name='Duration minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('service', models.CharField(max_length=500, verbose_name='Service')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tattoo_app.client')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
