# Generated by Django 4.1.2 on 2026-08-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0006_appointments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
