# Generated by Django 4.1.2 on 2026-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0007_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Заплановано'), ('completed', 'Завершено'), ('cancelled', 'Скасовано'), ('no_show', 'Клієнт не прийшов')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
